### ISSUE TITLE
error: #[feature] may not be used on the stable release channel [E0554]

### ISSUE THREAD

**Issue by mmacedoeu** [SkylerLipthay/interpolate_idents#13]
Got this trying to compile project with dependency to cpython:

.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.1.2/src/lib.rs:1:1: 1:45 error: #[feature] may not be used on the stable release channel [E0554]
.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.1.2/src/lib.rs:1 #![feature(plugin_registrar, rustc_private)]

rust stable:
rustc --version
rustc 1.11.0 (9b21dcd6a 2016-08-15)

cargo --version
cargo 0.12.0-nightly (6b98d1f 2016-07-04)

**Comment by SkylerLipthay** [comment]
Hi! This crate only supports Rust's nightly distribution channel, as stable Rust does not support [compiler plugins](https://doc.rust-lang.org/book/compiler-plugins.html) or the `#[feature]` attribute on which compiler plugins rely.

#6 proposes using a special work-around that `interpolate_idents` could implement using the `syntex` crate, but I haven't gotten around to this.

I have updated the README to include this information. Sorry for the confusion! Please reopen this issue if I am misunderstanding your problem.
