### ISSUE TITLE
Problem with leading underscore

### ISSUE THREAD

**Issue by johalun** [SkylerLipthay/interpolate_idents#25]
Hi
Thanks for this crate, its really saving my life right now :)

I have a problem though. 
[_ $name bla bla] does not work, (single underscore)
[__ $name bla bla] does work.  (double underscore)

Error when leading with single underscore is: 
```
error: expected identifier, found `[`
   --> src/macros.rs:104:24
    |
104 |               pub static [_ $module _depend_on_ $mdepend]: ksys::mod_depend = ksys::mod_depend {
    |                          ^
    | 
```

**Comment by SkylerLipthay** [comment]
Hey no problem. I just published `interpolate_idents 0.2.0` which should fix this problem for you.
