### ISSUE TITLE
Collision with #[] type attributes

### ISSUE THREAD

**Issue by johalun** [SkylerLipthay/interpolate_idents#26]
Hi

I have the following code inside a macro 
```
        interpolate_idents! {
            #[link_section = concat!("set_", "$set")]
            #[used]
            pub static [__set_ $set _sym_ $sym]: &ksys::$type = &($sym);
        }
```
If I put the attributes outside of interpolate_idents {} they get discarded (not visible in expanded code).
Having them inside generates error:
```
error: expected `[`, found `used`
   --> src/macros.rs:33:15
    |
33  |               #[used]
    |                 ^^^^
    | 
   ::: src/lib.rs
```
Would it be easy to make it ignore attributes?

**Comment by johalun** [comment]
Actually this line seem to work fine inside your macro.

`#[link_section = ".data"]`

**Comment by SkylerLipthay** [comment]
Just pushed `0.2.1` to fix this.

I'm surprised this only came up now. I'm sure there are also collisions with slice declarations, e.g. `let x = 1; let y = [x];`. There's definitely a way to refactor the parsing to make it sturdier, but this small exception for allowing attributes will be sufficient for now...

**Comment by johalun** [comment]
Thanks!! I realized I made a mistake by using concat!() inside an attribute which is not possible (yet). But I solved it another way.
