### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by NickeZ** [SkylerLipthay/interpolate_idents#27]
I have a crate [epics-sys](https://github.com/NickeZ/epics-sys/blob/niklas/nightly/src/lib.rs) which should export a macro that uses `interpolate_idents`. Currently I get the following error when I compile a crate that depends on `epics-sys`:

```
error: cannot find macro `interpolate_idents!` in this scope
  --> <epics_register_function macros>:2:1
   |
1  | / ( $ func : ident , $ type : ty ) => (
2  | | interpolate_idents ! {
   | | ^^^^^^^^^^^^^^^^^^
3  | | # [ no_mangle ] pub extern "C" fn $ func ( precord : * mut $ type ) -> :: std
4  | | :: os :: raw :: c_long {
...  |
14 | | std :: os :: raw :: c_void = [ register_func_ $ func ] as * const :: std :: os
15 | | :: raw :: c_void ; } )
   | |______________________- in this expansion of `epics_register_function!`
   |
  ::: src/lib.rs
   |
31 |   epics_register_function!( mySubInit, subRecord);
   |   ------------------------------------------------ in this macro invocation
```

Am I doing something wrong or do I need to add:

```
#![feature(plugin)]
#![plugin(interpolate_idents)]
```

to crate that depends on my crate?

**Comment by MauriceKayser** [comment]
I am currently facing the same "problem". Is the solution, like @NickeZ asked, to add the two lines to the crate which doesn't use `interpolate_idents` itself?

**Comment by SkylerLipthay** [comment]
Yes, unfortunately if I recall correctly the `interpolate_idents` dependency extends to any higher-level crates. I think this is just the way nested macros work. Honestly I haven't worked with this crate let alone procedural macros in a long time, so my memory may be a bit hazy... But this problem seems familiar to me. Apologies for the lackluster answer.

**Comment by gnzlbg** [comment]
`interpolate_idents` is now deprecated - please check out the `paste` crate for a replacement.
