### ISSUE TITLE
Failing on nightly

### ISSUE THREAD

**Issue by joshlf** [SkylerLipthay/interpolate_idents#30]
`interpolate_idents` is failing on today's nightly. See, e.g., the error from [this Travis build](https://travis-ci.org/ezrosent/allocators-rs/jobs/356020006#L2863):

```text
error[E0599]: no variant named `Underscore` found for type `syntax::parse::token::Token` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.2.2/src/lib.rs:39:52
   |
39 |                         TokenTree::Token(ref span, Token::Underscore) => {
   |                                                    ^^^^^^^^^^^^^^^^^ variant not found in `syntax::parse::token::Token`
```

**Comment by mb1986** [comment]
I think that I've found a problem. There was a [commit] removing `Underscore` token. Currently underscore character is treated as `Ident`. I've made a PR.

[commit]: https://github.com/rust-lang/rust/commit/5d06c890fececc6f6779cd65ca83cef4647b8fdd#diff-74b5ba63896c56c0964426955d2700d1

**Comment by SkylerLipthay** [comment]
0.2.3 has been released. Thank you both!
