### ISSUE TITLE
Could not find `small_vector` in `util`

### ISSUE THREAD

**Issue by gnzlbg** [SkylerLipthay/interpolate_idents#36]
--> /cargo/registry/src/github.com-1ecc6299db9ec823/interpolate_idents-0.2.5/src/parser_any_macro.rs:10:19
   |
10 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`
error: aborting due to previous error

**Comment by dtolnay** [comment]
It was moved to rustc_data_structures: https://github.com/rust-lang/rust/pull/53085.

**Comment by gnzlbg** [comment]
Yep. see #37 and #35 . I've published a fork on crates.io with the fix as a temporary workaround under `interpolate_idents_gnzlbg_fork`. No idea whether this is good or bad practice, or if there is a better convention for this, but the world was breaking apart and a git dependency wasn't good enough.

**Comment by SkylerLipthay** [comment]
Fixed by #35 and published `0.2.6`.

@gnzlbg Out of curiosity why was using a git dependency not good enough in your case?

**Comment by gnzlbg** [comment]
Because I needed other dependencies to keep on building on CI, and it was either patching the whole dependency graph, or just forking+patch+publish once. This polluted crates.io with an extra crate, and crates.io offers no ways to deal with that, but that's another issue.
